### ISSUE TITLE
Возвращается ошибка 403 при переходе по ссылке из письма об изменении пароля

### ISSUE THREAD

**Issue by Zvenova** [MyMindWorld/SpringServer#5]
## Шаги воспроизведения
1. Залогиниться на сайте http://127.0.0.1:8080/ScriptServer/login
2. Кликнуть по кнопке "Тут можно запросить изменение пароля"
3. Открыть почту, указанную в профиле пользователя
4. Открыть письмо с темой "Reset password on Script Server"
5. Кликнуть по ссылке, указанной в теле письма для смены пароля

## Ожидаемый результат:
Открывается страница с формой для смены пароля

## Фактический результат:
Открывается страница с ошибкой 403
![image](https://user-images.githubusercontent.com/63746856/117846053-c0cf3200-b289-11eb-83b4-d3897a756b2d.png)

-----
При тестировании было отмечено, что открытие этой ссылки в другом браузере или режиме инкогнито - открывает форму со сменой пароля. Возможно есть проблема с Cookies

**Comment by MyMindWorld** [comment]
@Zvenova Проверь, залил фикс

**Comment by Zvenova** [comment]
Работает, красавчик
