### ISSUE TITLE
Нет возможности восстановить "Username" по кнопке "Forgot Username / Password?" со страницы входа

### ISSUE THREAD

**Issue by Zvenova** [MyMindWorld/SpringServer#7]
## Шаги воспроизведения
1. Зайти на страницу входа http://127.0.0.1:8080/ScriptServer/login
2. Кликнуть по кнопке "Forgot Username / Password?"

## Ожидаемый результат:
Всплывает окошко для восстановления username или password

## Фактический результат:
Всплывает окошко для восстановления password
![image](https://user-images.githubusercontent.com/63746856/118356527-5dd9e580-b57e-11eb-8581-d997abb77817.png)

**Comment by MyMindWorld** [comment]
@Zvenova Проверь, запушил фикс

**Comment by MyMindWorld** [comment]
![image](https://user-images.githubusercontent.com/32519327/119278353-617c0500-bc2d-11eb-89eb-a47c00c17667.png)
Пофиксил?

**Comment by Zvenova** [comment]
Тип того
